export const POLYCODE_VSCODE_THEME = "polycode-vscode-dark";

export function definePolycodeMonacoTheme(monaco) {
  if (!monaco) return;

  monaco.editor.defineTheme(POLYCODE_VSCODE_THEME, {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "", foreground: "d4d4d4", background: "1e1e1e" },
      { token: "comment", foreground: "6a9955", fontStyle: "italic" },
      { token: "keyword", foreground: "569cd6" },
      { token: "number", foreground: "b5cea8" },
      { token: "string", foreground: "ce9178" },
      { token: "type", foreground: "4ec9b0" },
      { token: "class", foreground: "4ec9b0" },
      { token: "function", foreground: "dcdcaa" },
      { token: "variable", foreground: "9cdcfe" },
    ],
    colors: {
      "editor.background": "#1e1e1e",
      "editor.foreground": "#d4d4d4",
      "editorLineNumber.foreground": "#858585",
      "editorLineNumber.activeForeground": "#c6c6c6",
      "editorCursor.foreground": "#aeafad",
      "editor.selectionBackground": "#0ea5e980",
      "editor.selectionForeground": "#f8fbff",
      "editor.selectionHighlightBackground": "#0ea5e933",
      "editor.inactiveSelectionBackground": "#0ea5e94d",
      "editor.inactiveSelectionForeground": "#f8fbff",
      "editor.wordHighlightBackground": "#0ea5e926",
      "editor.wordHighlightStrongBackground": "#0ea5e940",
      "editor.lineHighlightBackground": "#2a2d2e",
      "editor.lineHighlightBorder": "#00000000",
      "editorBracketMatch.background": "#0064001a",
      "editorBracketMatch.border": "#888888",
      "editorIndentGuide.background1": "#404040",
      "editorIndentGuide.activeBackground1": "#707070",
      "editorGutter.background": "#1e1e1e",
      "editorWidget.background": "#252526",
      "editorSuggestWidget.background": "#252526",
      "editorSuggestWidget.border": "#454545",
      "editorSuggestWidget.selectedBackground": "#04395e",
      "input.background": "#3c3c3c",
      "focusBorder": "#007acc",
      "scrollbarSlider.background": "#79797966",
      "scrollbarSlider.hoverBackground": "#646464b3",
      "scrollbarSlider.activeBackground": "#bfbfbf66",
    },
  });
}

export function getVSCodeEditorOptions({
  fontSize = 14,
  wordWrap = false,
  readOnly = false,
} = {}) {
  return {
    readOnly,
    fontSize,
    fontFamily: "'Cascadia Code','JetBrains Mono','Fira Code',Consolas,monospace",
    fontLigatures: true,
    lineHeight: 21,
    letterSpacing: 0,
    tabSize: 4,
    insertSpaces: true,
    detectIndentation: false,
    autoIndent: "full",
    formatOnType: true,
    formatOnPaste: true,
    autoClosingBrackets: "always",
    autoClosingQuotes: "always",
    autoSurround: "languageDefined",
    lineNumbers: "on",
    glyphMargin: false,
    folding: true,
    foldingHighlight: true,
    renderLineHighlight: "all",
    matchBrackets: "always",
    bracketPairColorization: { enabled: true },
    guides: {
      indentation: true,
      bracketPairs: true,
      bracketPairsHorizontal: true,
      highlightActiveIndentation: true,
    },
    cursorBlinking: "smooth",
    cursorSmoothCaretAnimation: "on",
    cursorWidth: 2,
    selectionHighlight: true,
    occurrencesHighlight: "singleFile",
    renderWhitespace: "selection",
    minimap: { enabled: false },
    wordWrap: wordWrap ? "on" : "off",
    scrollBeyondLastLine: false,
    smoothScrolling: true,
    automaticLayout: true,
    padding: { top: 14, bottom: 14 },
    overviewRulerBorder: false,
    hideCursorInOverviewRuler: true,
  };
}
